namespace NetworkHighlightOverlay.Code.ModOptions
{
    public static class HighlightCategoryCatalog
    {
        public static readonly HighlightCategoryDefinition[] All = new[]
        {
            new HighlightCategoryDefinition(
                HighlightCategoryId.PedestrianPaths,
                "Pedestrian paths",
                "Pedestrian paths",
                "Highlight pedestrian paths",
                "SubBarBeautificationPedestrianZoneEssentials",
                config => config.HighlightPedestrianPaths,
                (config, value) => config.HighlightPedestrianPaths = value,
                config => config.PedestrianPathsHue,
                (config, value) => config.PedestrianPathsHue = value),
            new HighlightCategoryDefinition(
                HighlightCategoryId.PinkPaths,
                "Pink paths",
                "Pink paths",
                "Highlight pink paths",
                "SubBarRoadsMaintenance",
                config => config.HighlightPinkPaths,
                (config, value) => config.HighlightPinkPaths = value,
                config => config.PinkPathsHue,
                (config, value) => config.PinkPathsHue = value),
            new HighlightCategoryDefinition(
                HighlightCategoryId.TerraformingNetworks,
                "Terraforming networks",
                "Terraforming networks",
                "Highlight terraforming networks",
                "ToolbarIconLandscaping",
                config => config.HighlightTerraformingNetworks,
                (config, value) => config.HighlightTerraformingNetworks = value,
                config => config.TerraformingNetworksHue,
                (config, value) => config.TerraformingNetworksHue = value),
            new HighlightCategoryDefinition(
                HighlightCategoryId.Roads,
                "Roads",
                "Roads",
                "Highlight roads",
                "SubBarRoadsSmall",
                config => config.HighlightRoads,
                (config, value) => config.HighlightRoads = value,
                config => config.RoadsHue,
                (config, value) => config.RoadsHue = value),
            new HighlightCategoryDefinition(
                HighlightCategoryId.Highways,
                "Highways",
                "Highways",
                "Highlight highways",
                "SubBarRoadsHighway",
                config => config.HighlightHighways,
                (config, value) => config.HighlightHighways = value,
                config => config.HighwaysHue,
                (config, value) => config.HighwaysHue = value),
            new HighlightCategoryDefinition(
                HighlightCategoryId.TrainTracks,
                "Train tracks",
                "Train tracks",
                "Highlight train tracks",
                "SubBarPublicTransportTrain",
                config => config.HighlightTrainTracks,
                (config, value) => config.HighlightTrainTracks = value,
                config => config.TrainTracksHue,
                (config, value) => config.TrainTracksHue = value),
            new HighlightCategoryDefinition(
                HighlightCategoryId.MetroTracks,
                "Metro tracks",
                "Metro tracks",
                "Highlight metro tracks",
                "SubBarPublicTransportMetro",
                config => config.HighlightMetroTracks,
                (config, value) => config.HighlightMetroTracks = value,
                config => config.MetroTracksHue,
                (config, value) => config.MetroTracksHue = value),
            new HighlightCategoryDefinition(
                HighlightCategoryId.TramTracks,
                "Tram tracks",
                "Tram and Trolley tracks",
                "Highlight tram tracks",
                "SubBarPublicTransportTram",
                config => config.HighlightTramTracks,
                (config, value) => config.HighlightTramTracks = value,
                config => config.TramTracksHue,
                (config, value) => config.TramTracksHue = value),
            new HighlightCategoryDefinition(
                HighlightCategoryId.MonorailTracks,
                "Monorail tracks",
                "Monorail tracks",
                "Highlight monorail tracks",
                "SubBarPublicTransportMonorail",
                config => config.HighlightMonorailTracks,
                (config, value) => config.HighlightMonorailTracks = value,
                config => config.MonorailHue,
                (config, value) => config.MonorailHue = value),
            new HighlightCategoryDefinition(
                HighlightCategoryId.CableCars,
                "Cable cars",
                "Cable car paths",
                "Highlight cable car paths",
                "SubBarPublicTransportCableCar",
                config => config.HighlightCableCars,
                (config, value) => config.HighlightCableCars = value,
                config => config.CableCarsHue,
                (config, value) => config.CableCarsHue = value)
        };
    }
}
